Fix -Werror=ignored-attributes error when compiling with g++
by added the warning to the WERR=1 ignore list.

    g++ -D_POSIX_SOURCE -Os -std=c++17 -MMD -Wall -Wextra -Werror -Wno-error=unused-variable -Wno-error=unused-result -Wno-error=unused-parameter -Wno-error=unused-function -Wno-error=unused-value -Wold-style-cast -Wnon-virtual-dtor -fno-exceptions -fno-rtti -c -o src/wiz/wiz.o src/wiz/wiz.cpp -Isrc
    In file included from src/wiz/wiz.cpp:19:
    src/wiz/utility/reader.h:39:62: error: ignoring attributes on template argument ‘int (*)(FILE*)’ [-Werror=ignored-attributes]
       39 |             std::unique_ptr<std::FILE, decltype(&std::fclose)> file;
          |                                                              ^