Fix ‘SIZE_MAX’ was not declared in this scope g++ error
    g++ -D_POSIX_SOURCE -Os -std=c++17 -MMD -Wall -Wextra -Werror -Wno-error=unused-variable -Wno-error=unused-result -Wno-error=unused-parameter -Wno-error=unused-function -Wno-error=unused-value -Wno-ignored-attributes -Wold-style-cast -Wnon-virtual-dtor -fno-exceptions -fno-rtti -c -o src/wiz/parser/scanner.o src/wiz/parser/scanner.cpp -Isrc
    In file included from src/wiz/utility/text.h:9,
                     from src/wiz/parser/scanner.cpp:4:
    src/wiz/utility/string_view.h:72:76: error: ‘SIZE_MAX’ was not declared in this scope
       72 |             constexpr StringView sub(std::size_t index, std::size_t size = SIZE_MAX) const {
          |                                                                            ^~~~~~~~